server:
  port: 8081


spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/event
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    enabled: true
    path: /api-docs


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
    register-with-eureka: true
    fetch-registry: true

